### PR TITLE
some correction suggestions for the backend spec

### PR DESCRIPTION
**Pull request by mfelsche**
I have been adding some suggestions for corrections of the backend spec while
developing an erlang example app, which comes in a different PR.

let's discuss

### CODE REVIEW

**Comment by mfelsche** [comment]
ok, nice! :)
lets use 201 with response body and post with JSON body for search.
i'll update this PR and then change my erlang app accordingly

**Comment by chaudum** [comment]
PURRFECT

**Comment by mfelsche** [comment]
updated.
sorry for rebasing all the old commits away, but i wanted to keep the single commits clean.

**Comment by chaudum** [comment]
ack
ack

**Pull request merged**
