### PR TITLE
Config user database for CrateDB versions 2.1.x or later

### PR DESCRIPTION
**Pull request by toanalien**
ref: https://crate.io/docs/clients/jdbc/en/latest/connect.html#id2

### CODE REVIEW

**Comment by joemoe** [comment]
hi @toanalien, thanks for you PR. our engineers will have a look at it. would it be possible for you to sign our cla? https://crate.io/community/contribute/cla/
thanks, joe

**Comment by toanalien** [comment]
I already signed, thanks @joemoe

**Comment by joemoe** [comment]
fantastic. thanks a lot.

**Comment by lukasbals** [comment]
fixed in this pull request --> https://github.com/crate/crate-sample-apps/pull/71

**Pull request closed without merging**
